version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5500:5500"
    environment:
      ES_HOST: elasticsearch
      DB_HOST: "sql6.freesqldatabase.com"
      DB_USER: "sql6684568"
      DB_PASSWORD: "QaUnlRWwiQ"
      DB_DATABASE: "sql6684568"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
    ports:
      - "9300:9200"
    
  
  frontend:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5500
    depends_on:
      - backend

volumes:
  elastic_data: {}


