version: '3'

services:
  backend:
    build: .
    ports:
      - "5500:5500"
    environment:
      DB_HOST: "sql6.freesqldatabase.com"
      DB_USER: "sql6684568"
      DB_PASSWORD: "QaUnlRWwiQ"
      DB_DATABASE: "sql6684568"
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "ecommerse"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
